// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v7.34.1
// source: aggregate.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Aggregate is the SignedAggregateAndProof wire message (~505 B), published on the global
// beacon_aggregate_and_proof topic at the aggregate deadline. A committee has m distinct
// aggregates (agg_idx 0..m-1); every aggregator of the committee publishes the same m,
// byte-for-byte. There is deliberately NO aggregator/origin field: identical bytes ⇒
// identical content-hash message-id ⇒ gossipsub dedups the copies (the multi-source model).
type Aggregate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slot          uint32                 `protobuf:"varint,1,opt,name=slot,proto3" json:"slot,omitempty"`
	Subnet        uint32                 `protobuf:"varint,2,opt,name=subnet,proto3" json:"subnet,omitempty"`               // committee → subnet
	AggIdx        uint32                 `protobuf:"varint,3,opt,name=agg_idx,json=aggIdx,proto3" json:"agg_idx,omitempty"` // which of the committee's m aggregates (0..m-1)
	Payload       []byte                 `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`              // random filler so the marshaled message hits ~505 B
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Aggregate) Reset() {
	*x = Aggregate{}
	mi := &file_aggregate_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Aggregate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Aggregate) ProtoMessage() {}

func (x *Aggregate) ProtoReflect() protoreflect.Message {
	mi := &file_aggregate_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Aggregate.ProtoReflect.Descriptor instead.
func (*Aggregate) Descriptor() ([]byte, []int) {
	return file_aggregate_proto_rawDescGZIP(), []int{0}
}

func (x *Aggregate) GetSlot() uint32 {
	if x != nil {
		return x.Slot
	}
	return 0
}

func (x *Aggregate) GetSubnet() uint32 {
	if x != nil {
		return x.Subnet
	}
	return 0
}

func (x *Aggregate) GetAggIdx() uint32 {
	if x != nil {
		return x.AggIdx
	}
	return 0
}

func (x *Aggregate) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

var File_aggregate_proto protoreflect.FileDescriptor

const file_aggregate_proto_rawDesc = "" +
	"\n" +
	"\x0faggregate.proto\x12\x05block\"j\n" +
	"\tAggregate\x12\x12\n" +
	"\x04slot\x18\x01 \x01(\rR\x04slot\x12\x16\n" +
	"\x06subnet\x18\x02 \x01(\rR\x06subnet\x12\x17\n" +
	"\aagg_idx\x18\x03 \x01(\rR\x06aggIdx\x12\x18\n" +
	"\apayload\x18\x04 \x01(\fR\apayloadB\x1fZ\x1dgithub.com/ethp2p/slot-sim/pbb\x06proto3"

var (
	file_aggregate_proto_rawDescOnce sync.Once
	file_aggregate_proto_rawDescData []byte
)

func file_aggregate_proto_rawDescGZIP() []byte {
	file_aggregate_proto_rawDescOnce.Do(func() {
		file_aggregate_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_aggregate_proto_rawDesc), len(file_aggregate_proto_rawDesc)))
	})
	return file_aggregate_proto_rawDescData
}

var file_aggregate_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_aggregate_proto_goTypes = []any{
	(*Aggregate)(nil), // 0: block.Aggregate
}
var file_aggregate_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_aggregate_proto_init() }
func file_aggregate_proto_init() {
	if File_aggregate_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_aggregate_proto_rawDesc), len(file_aggregate_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_aggregate_proto_goTypes,
		DependencyIndexes: file_aggregate_proto_depIdxs,
		MessageInfos:      file_aggregate_proto_msgTypes,
	}.Build()
	File_aggregate_proto = out.File
	file_aggregate_proto_goTypes = nil
	file_aggregate_proto_depIdxs = nil
}
