// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v7.34.1
// source: attestation.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Attestation is the SingleAttestation wire message (~240 B), one per attester per
// slot, published on its committee's subnet. voted_origin records the block it voted
// for (the proposer node number) or a sentinel for the prior head — the measurable
// output of the block→attestation causal edge.
type Attestation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slot          uint32                 `protobuf:"varint,1,opt,name=slot,proto3" json:"slot,omitempty"`
	Subnet        uint32                 `protobuf:"varint,2,opt,name=subnet,proto3" json:"subnet,omitempty"`                              // committee → subnet
	Val           uint32                 `protobuf:"varint,3,opt,name=val,proto3" json:"val,omitempty"`                                    // global validator index — stable identity
	Origin        uint32                 `protobuf:"varint,4,opt,name=origin,proto3" json:"origin,omitempty"`                              // publishing node number (gossip origin; for the loopback skip)
	VotedOrigin   uint32                 `protobuf:"varint,5,opt,name=voted_origin,json=votedOrigin,proto3" json:"voted_origin,omitempty"` // voted block's origin, or a sentinel (max uint32) for prior head
	Payload       []byte                 `protobuf:"bytes,6,opt,name=payload,proto3" json:"payload,omitempty"`                             // random filler so the marshaled message hits ~240 B
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Attestation) Reset() {
	*x = Attestation{}
	mi := &file_attestation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Attestation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Attestation) ProtoMessage() {}

func (x *Attestation) ProtoReflect() protoreflect.Message {
	mi := &file_attestation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Attestation.ProtoReflect.Descriptor instead.
func (*Attestation) Descriptor() ([]byte, []int) {
	return file_attestation_proto_rawDescGZIP(), []int{0}
}

func (x *Attestation) GetSlot() uint32 {
	if x != nil {
		return x.Slot
	}
	return 0
}

func (x *Attestation) GetSubnet() uint32 {
	if x != nil {
		return x.Subnet
	}
	return 0
}

func (x *Attestation) GetVal() uint32 {
	if x != nil {
		return x.Val
	}
	return 0
}

func (x *Attestation) GetOrigin() uint32 {
	if x != nil {
		return x.Origin
	}
	return 0
}

func (x *Attestation) GetVotedOrigin() uint32 {
	if x != nil {
		return x.VotedOrigin
	}
	return 0
}

func (x *Attestation) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

var File_attestation_proto protoreflect.FileDescriptor

const file_attestation_proto_rawDesc = "" +
	"\n" +
	"\x11attestation.proto\x12\x05block\"\xa0\x01\n" +
	"\vAttestation\x12\x12\n" +
	"\x04slot\x18\x01 \x01(\rR\x04slot\x12\x16\n" +
	"\x06subnet\x18\x02 \x01(\rR\x06subnet\x12\x10\n" +
	"\x03val\x18\x03 \x01(\rR\x03val\x12\x16\n" +
	"\x06origin\x18\x04 \x01(\rR\x06origin\x12!\n" +
	"\fvoted_origin\x18\x05 \x01(\rR\vvotedOrigin\x12\x18\n" +
	"\apayload\x18\x06 \x01(\fR\apayloadB\x1fZ\x1dgithub.com/ethp2p/slot-sim/pbb\x06proto3"

var (
	file_attestation_proto_rawDescOnce sync.Once
	file_attestation_proto_rawDescData []byte
)

func file_attestation_proto_rawDescGZIP() []byte {
	file_attestation_proto_rawDescOnce.Do(func() {
		file_attestation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_attestation_proto_rawDesc), len(file_attestation_proto_rawDesc)))
	})
	return file_attestation_proto_rawDescData
}

var file_attestation_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_attestation_proto_goTypes = []any{
	(*Attestation)(nil), // 0: block.Attestation
}
var file_attestation_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_attestation_proto_init() }
func file_attestation_proto_init() {
	if File_attestation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_attestation_proto_rawDesc), len(file_attestation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_attestation_proto_goTypes,
		DependencyIndexes: file_attestation_proto_depIdxs,
		MessageInfos:      file_attestation_proto_msgTypes,
	}.Build()
	File_attestation_proto = out.File
	file_attestation_proto_goTypes = nil
	file_attestation_proto_depIdxs = nil
}
