// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v7.34.1
// source: column.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Column is the DataColumnSidecar wire message (~12.9 KiB at blobs=6), one per column
// subnet per slot. The proposer erasure-codes the block into num_columns columns and
// publishes one on each column topic in a t=0 burst; a node receives the columns on the
// subnets it custodies. column is the column / subnet index; origin is the proposer node
// (gossip origin, for the loopback skip).
type Column struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slot          uint32                 `protobuf:"varint,1,opt,name=slot,proto3" json:"slot,omitempty"`
	Column        uint32                 `protobuf:"varint,2,opt,name=column,proto3" json:"column,omitempty"`  // column / subnet index, 0 .. num_columns-1
	Origin        uint32                 `protobuf:"varint,3,opt,name=origin,proto3" json:"origin,omitempty"`  // proposer node (gossip origin; for the loopback skip)
	Payload       []byte                 `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"` // random filler so the marshaled message ≈ blobs*2144 + 356 bytes
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Column) Reset() {
	*x = Column{}
	mi := &file_column_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Column) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Column) ProtoMessage() {}

func (x *Column) ProtoReflect() protoreflect.Message {
	mi := &file_column_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Column.ProtoReflect.Descriptor instead.
func (*Column) Descriptor() ([]byte, []int) {
	return file_column_proto_rawDescGZIP(), []int{0}
}

func (x *Column) GetSlot() uint32 {
	if x != nil {
		return x.Slot
	}
	return 0
}

func (x *Column) GetColumn() uint32 {
	if x != nil {
		return x.Column
	}
	return 0
}

func (x *Column) GetOrigin() uint32 {
	if x != nil {
		return x.Origin
	}
	return 0
}

func (x *Column) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

var File_column_proto protoreflect.FileDescriptor

const file_column_proto_rawDesc = "" +
	"\n" +
	"\fcolumn.proto\x12\x05block\"f\n" +
	"\x06Column\x12\x12\n" +
	"\x04slot\x18\x01 \x01(\rR\x04slot\x12\x16\n" +
	"\x06column\x18\x02 \x01(\rR\x06column\x12\x16\n" +
	"\x06origin\x18\x03 \x01(\rR\x06origin\x12\x18\n" +
	"\apayload\x18\x04 \x01(\fR\apayloadB\x1fZ\x1dgithub.com/ethp2p/slot-sim/pbb\x06proto3"

var (
	file_column_proto_rawDescOnce sync.Once
	file_column_proto_rawDescData []byte
)

func file_column_proto_rawDescGZIP() []byte {
	file_column_proto_rawDescOnce.Do(func() {
		file_column_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_column_proto_rawDesc), len(file_column_proto_rawDesc)))
	})
	return file_column_proto_rawDescData
}

var file_column_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_column_proto_goTypes = []any{
	(*Column)(nil), // 0: block.Column
}
var file_column_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_column_proto_init() }
func file_column_proto_init() {
	if File_column_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_column_proto_rawDesc), len(file_column_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_column_proto_goTypes,
		DependencyIndexes: file_column_proto_depIdxs,
		MessageInfos:      file_column_proto_msgTypes,
	}.Build()
	File_column_proto = out.File
	file_column_proto_goTypes = nil
	file_column_proto_depIdxs = nil
}
