// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v7.34.1
// source: decoupled.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ACVote is the availability-chain vote (~240 B), one per VRF-selected validator per slot,
// published on the single global availability_vote topic (no subnets, no committees, no
// aggregation — every node downloads all). Like an attestation, it is block→vote coupled and
// data-availability gated, so voted_origin records the voted block's origin (proposer node) or a
// sentinel (max uint32) for the prior head — the measurable output of the column gate over the
// global voter set. There is deliberately no subnet field: the topic is global.
type ACVote struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slot          uint32                 `protobuf:"varint,1,opt,name=slot,proto3" json:"slot,omitempty"`
	Val           uint32                 `protobuf:"varint,2,opt,name=val,proto3" json:"val,omitempty"`                                    // global validator index — the stable identity
	Origin        uint32                 `protobuf:"varint,3,opt,name=origin,proto3" json:"origin,omitempty"`                              // publishing node (gossip origin; for the loopback skip)
	VotedOrigin   uint32                 `protobuf:"varint,4,opt,name=voted_origin,json=votedOrigin,proto3" json:"voted_origin,omitempty"` // voted block's origin, or a sentinel (max uint32) for prior head
	Payload       []byte                 `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"`                             // random filler so the marshaled message ≈ 240 B
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ACVote) Reset() {
	*x = ACVote{}
	mi := &file_decoupled_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ACVote) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ACVote) ProtoMessage() {}

func (x *ACVote) ProtoReflect() protoreflect.Message {
	mi := &file_decoupled_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ACVote.ProtoReflect.Descriptor instead.
func (*ACVote) Descriptor() ([]byte, []int) {
	return file_decoupled_proto_rawDescGZIP(), []int{0}
}

func (x *ACVote) GetSlot() uint32 {
	if x != nil {
		return x.Slot
	}
	return 0
}

func (x *ACVote) GetVal() uint32 {
	if x != nil {
		return x.Val
	}
	return 0
}

func (x *ACVote) GetOrigin() uint32 {
	if x != nil {
		return x.Origin
	}
	return 0
}

func (x *ACVote) GetVotedOrigin() uint32 {
	if x != nil {
		return x.VotedOrigin
	}
	return 0
}

func (x *ACVote) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

// FinalityVote is the finality-chain vote (~226 B), one per validator a node hosts, published on
// the node's stable finality subnet at a fixed offset into the finality slot. It is
// dissemination-only this cut (no fork-choice outcome measured): un-gated by data availability and
// not block-coupled, so it carries no voted_origin. val is the identity (one vote per validator);
// a node hosting m selected validators publishes m votes (k-multiplicity, like attestations).
type FinalityVote struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FinalitySlot  uint32                 `protobuf:"varint,1,opt,name=finality_slot,json=finalitySlot,proto3" json:"finality_slot,omitempty"`
	Subnet        uint32                 `protobuf:"varint,2,opt,name=subnet,proto3" json:"subnet,omitempty"`  // this node's stable finality subnet, 0 .. fs_subnets-1
	Val           uint32                 `protobuf:"varint,3,opt,name=val,proto3" json:"val,omitempty"`        // global validator index — the identity (one vote per validator)
	Origin        uint32                 `protobuf:"varint,4,opt,name=origin,proto3" json:"origin,omitempty"`  // publishing member node (gossip origin; for the loopback skip)
	Payload       []byte                 `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"` // random filler so the marshaled message ≈ 226 B
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FinalityVote) Reset() {
	*x = FinalityVote{}
	mi := &file_decoupled_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinalityVote) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinalityVote) ProtoMessage() {}

func (x *FinalityVote) ProtoReflect() protoreflect.Message {
	mi := &file_decoupled_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinalityVote.ProtoReflect.Descriptor instead.
func (*FinalityVote) Descriptor() ([]byte, []int) {
	return file_decoupled_proto_rawDescGZIP(), []int{1}
}

func (x *FinalityVote) GetFinalitySlot() uint32 {
	if x != nil {
		return x.FinalitySlot
	}
	return 0
}

func (x *FinalityVote) GetSubnet() uint32 {
	if x != nil {
		return x.Subnet
	}
	return 0
}

func (x *FinalityVote) GetVal() uint32 {
	if x != nil {
		return x.Val
	}
	return 0
}

func (x *FinalityVote) GetOrigin() uint32 {
	if x != nil {
		return x.Origin
	}
	return 0
}

func (x *FinalityVote) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

// FinalityAggregate is the finality-chain aggregate, published on the single global
// finality_aggregate_and_proof topic at the aggregation deadline. Each subnet has fs_aggregators
// aggregators per finality slot; every aggregator publishes one distinct aggregate. Its size
// scales with the subnet's voting population: base 328 B + a ceil(validators_per_subnet/8)
// aggregation bitfield. origin carries the aggregator node, which both makes the aggregate
// distinct (so gossipsub does not dedup them) and is the gossip origin for the loopback skip.
type FinalityAggregate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FinalitySlot  uint32                 `protobuf:"varint,1,opt,name=finality_slot,json=finalitySlot,proto3" json:"finality_slot,omitempty"`
	Subnet        uint32                 `protobuf:"varint,2,opt,name=subnet,proto3" json:"subnet,omitempty"`  // subcommittee (for distinctness; the topic is global)
	Origin        uint32                 `protobuf:"varint,3,opt,name=origin,proto3" json:"origin,omitempty"`  // aggregator node (its key makes the aggregate distinct; gossip origin)
	Payload       []byte                 `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"` // random filler sized to base + the scaled aggregation bitfield
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FinalityAggregate) Reset() {
	*x = FinalityAggregate{}
	mi := &file_decoupled_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinalityAggregate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinalityAggregate) ProtoMessage() {}

func (x *FinalityAggregate) ProtoReflect() protoreflect.Message {
	mi := &file_decoupled_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinalityAggregate.ProtoReflect.Descriptor instead.
func (*FinalityAggregate) Descriptor() ([]byte, []int) {
	return file_decoupled_proto_rawDescGZIP(), []int{2}
}

func (x *FinalityAggregate) GetFinalitySlot() uint32 {
	if x != nil {
		return x.FinalitySlot
	}
	return 0
}

func (x *FinalityAggregate) GetSubnet() uint32 {
	if x != nil {
		return x.Subnet
	}
	return 0
}

func (x *FinalityAggregate) GetOrigin() uint32 {
	if x != nil {
		return x.Origin
	}
	return 0
}

func (x *FinalityAggregate) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

var File_decoupled_proto protoreflect.FileDescriptor

const file_decoupled_proto_rawDesc = "" +
	"\n" +
	"\x0fdecoupled.proto\x12\x05block\"\x83\x01\n" +
	"\x06ACVote\x12\x12\n" +
	"\x04slot\x18\x01 \x01(\rR\x04slot\x12\x10\n" +
	"\x03val\x18\x02 \x01(\rR\x03val\x12\x16\n" +
	"\x06origin\x18\x03 \x01(\rR\x06origin\x12!\n" +
	"\fvoted_origin\x18\x04 \x01(\rR\vvotedOrigin\x12\x18\n" +
	"\apayload\x18\x05 \x01(\fR\apayload\"\x8f\x01\n" +
	"\fFinalityVote\x12#\n" +
	"\rfinality_slot\x18\x01 \x01(\rR\ffinalitySlot\x12\x16\n" +
	"\x06subnet\x18\x02 \x01(\rR\x06subnet\x12\x10\n" +
	"\x03val\x18\x03 \x01(\rR\x03val\x12\x16\n" +
	"\x06origin\x18\x04 \x01(\rR\x06origin\x12\x18\n" +
	"\apayload\x18\x05 \x01(\fR\apayload\"\x82\x01\n" +
	"\x11FinalityAggregate\x12#\n" +
	"\rfinality_slot\x18\x01 \x01(\rR\ffinalitySlot\x12\x16\n" +
	"\x06subnet\x18\x02 \x01(\rR\x06subnet\x12\x16\n" +
	"\x06origin\x18\x03 \x01(\rR\x06origin\x12\x18\n" +
	"\apayload\x18\x04 \x01(\fR\apayloadB\x1fZ\x1dgithub.com/ethp2p/slot-sim/pbb\x06proto3"

var (
	file_decoupled_proto_rawDescOnce sync.Once
	file_decoupled_proto_rawDescData []byte
)

func file_decoupled_proto_rawDescGZIP() []byte {
	file_decoupled_proto_rawDescOnce.Do(func() {
		file_decoupled_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_decoupled_proto_rawDesc), len(file_decoupled_proto_rawDesc)))
	})
	return file_decoupled_proto_rawDescData
}

var file_decoupled_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_decoupled_proto_goTypes = []any{
	(*ACVote)(nil),            // 0: block.ACVote
	(*FinalityVote)(nil),      // 1: block.FinalityVote
	(*FinalityAggregate)(nil), // 2: block.FinalityAggregate
}
var file_decoupled_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_decoupled_proto_init() }
func file_decoupled_proto_init() {
	if File_decoupled_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_decoupled_proto_rawDesc), len(file_decoupled_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_decoupled_proto_goTypes,
		DependencyIndexes: file_decoupled_proto_depIdxs,
		MessageInfos:      file_decoupled_proto_msgTypes,
	}.Build()
	File_decoupled_proto = out.File
	file_decoupled_proto_goTypes = nil
	file_decoupled_proto_depIdxs = nil
}
