// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v7.35.1
// source: epbs.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ConsensusBlock is the ePBS proposer message (Gloas beacon_block): the small consensus
// block carrying the builder's bid, no execution payload. payload carries random filler
// sized so the marshaled message hits the target byte count.
type ConsensusBlock struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slot          uint32                 `protobuf:"varint,1,opt,name=slot,proto3" json:"slot,omitempty"`
	Origin        uint32                 `protobuf:"varint,2,opt,name=origin,proto3" json:"origin,omitempty"`  // publishing node number (the proposer)
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"` // filler sized so the marshaled ConsensusBlock == target
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsensusBlock) Reset() {
	*x = ConsensusBlock{}
	mi := &file_epbs_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsensusBlock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsensusBlock) ProtoMessage() {}

func (x *ConsensusBlock) ProtoReflect() protoreflect.Message {
	mi := &file_epbs_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsensusBlock.ProtoReflect.Descriptor instead.
func (*ConsensusBlock) Descriptor() ([]byte, []int) {
	return file_epbs_proto_rawDescGZIP(), []int{0}
}

func (x *ConsensusBlock) GetSlot() uint32 {
	if x != nil {
		return x.Slot
	}
	return 0
}

func (x *ConsensusBlock) GetOrigin() uint32 {
	if x != nil {
		return x.Origin
	}
	return 0
}

func (x *ConsensusBlock) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

// ExecutionPayload is the ePBS builder reveal (Gloas execution_payload topic,
// SignedExecutionPayloadEnvelope): the big message, published 0.5-1s after the
// consensus block by the same node (the proposer plays the builder).
type ExecutionPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slot          uint32                 `protobuf:"varint,1,opt,name=slot,proto3" json:"slot,omitempty"`
	Origin        uint32                 `protobuf:"varint,2,opt,name=origin,proto3" json:"origin,omitempty"`  // publishing node number (proposer-as-builder)
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"` // filler sized so the marshaled ExecutionPayload == target
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecutionPayload) Reset() {
	*x = ExecutionPayload{}
	mi := &file_epbs_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutionPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionPayload) ProtoMessage() {}

func (x *ExecutionPayload) ProtoReflect() protoreflect.Message {
	mi := &file_epbs_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionPayload.ProtoReflect.Descriptor instead.
func (*ExecutionPayload) Descriptor() ([]byte, []int) {
	return file_epbs_proto_rawDescGZIP(), []int{1}
}

func (x *ExecutionPayload) GetSlot() uint32 {
	if x != nil {
		return x.Slot
	}
	return 0
}

func (x *ExecutionPayload) GetOrigin() uint32 {
	if x != nil {
		return x.Origin
	}
	return 0
}

func (x *ExecutionPayload) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

var File_epbs_proto protoreflect.FileDescriptor

const file_epbs_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"epbs.proto\x12\x04epbs\"V\n" +
	"\x0eConsensusBlock\x12\x12\n" +
	"\x04slot\x18\x01 \x01(\rR\x04slot\x12\x16\n" +
	"\x06origin\x18\x02 \x01(\rR\x06origin\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\"X\n" +
	"\x10ExecutionPayload\x12\x12\n" +
	"\x04slot\x18\x01 \x01(\rR\x04slot\x12\x16\n" +
	"\x06origin\x18\x02 \x01(\rR\x06origin\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayloadB\x1fZ\x1dgithub.com/ethp2p/slot-sim/pbb\x06proto3"

var (
	file_epbs_proto_rawDescOnce sync.Once
	file_epbs_proto_rawDescData []byte
)

func file_epbs_proto_rawDescGZIP() []byte {
	file_epbs_proto_rawDescOnce.Do(func() {
		file_epbs_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_epbs_proto_rawDesc), len(file_epbs_proto_rawDesc)))
	})
	return file_epbs_proto_rawDescData
}

var file_epbs_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_epbs_proto_goTypes = []any{
	(*ConsensusBlock)(nil),   // 0: epbs.ConsensusBlock
	(*ExecutionPayload)(nil), // 1: epbs.ExecutionPayload
}
var file_epbs_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_epbs_proto_init() }
func file_epbs_proto_init() {
	if File_epbs_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_epbs_proto_rawDesc), len(file_epbs_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_epbs_proto_goTypes,
		DependencyIndexes: file_epbs_proto_depIdxs,
		MessageInfos:      file_epbs_proto_msgTypes,
	}.Build()
	File_epbs_proto = out.File
	file_epbs_proto_goTypes = nil
	file_epbs_proto_depIdxs = nil
}
