// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v7.34.1
// source: partial.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PartialAttData is the shared attestation_data: the vote + filler. Deterministically built
// (all-ones filler) so every attester voting the same way produces byte-identical data.
// voted_origin: the voted block's origin, the prior-head sentinel (max uint32), or 0 for
// vote-free kinds (finality votes this cut). Receivers never need to parse it (identity comes
// from (topic, group, position)); parsing for the vote is available for debugging.
type PartialAttData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slot          uint32                 `protobuf:"varint,1,opt,name=slot,proto3" json:"slot,omitempty"` // the group key (slot / round key), for debuggability + uniqueness
	Subnet        uint32                 `protobuf:"varint,2,opt,name=subnet,proto3" json:"subnet,omitempty"`
	VotedOrigin   uint32                 `protobuf:"varint,3,opt,name=voted_origin,json=votedOrigin,proto3" json:"voted_origin,omitempty"`
	Payload       []byte                 `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"` // filler to attestation_data_size (default 128 ≈ real AttestationData)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PartialAttData) Reset() {
	*x = PartialAttData{}
	mi := &file_partial_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PartialAttData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PartialAttData) ProtoMessage() {}

func (x *PartialAttData) ProtoReflect() protoreflect.Message {
	mi := &file_partial_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PartialAttData.ProtoReflect.Descriptor instead.
func (*PartialAttData) Descriptor() ([]byte, []int) {
	return file_partial_proto_rawDescGZIP(), []int{0}
}

func (x *PartialAttData) GetSlot() uint32 {
	if x != nil {
		return x.Slot
	}
	return 0
}

func (x *PartialAttData) GetSubnet() uint32 {
	if x != nil {
		return x.Subnet
	}
	return 0
}

func (x *PartialAttData) GetVotedOrigin() uint32 {
	if x != nil {
		return x.VotedOrigin
	}
	return 0
}

func (x *PartialAttData) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

// BatchedAttestation carries every held vote of one (attestation_data) bucket a peer is owed.
type BatchedAttestation struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AttestationData []byte                 `protobuf:"bytes,1,opt,name=attestation_data,json=attestationData,proto3" json:"attestation_data,omitempty"`         // marshaled PartialAttData (opaque to the transport)
	AttestorIndices []uint32               `protobuf:"varint,2,rep,packed,name=attestor_indices,json=attestorIndices,proto3" json:"attestor_indices,omitempty"` // committee positions, ascending; < committee size
	Signatures      [][]byte               `protobuf:"bytes,3,rep,name=signatures,proto3" json:"signatures,omitempty"`                                          // one per index, signature_size B filler each
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *BatchedAttestation) Reset() {
	*x = BatchedAttestation{}
	mi := &file_partial_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchedAttestation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchedAttestation) ProtoMessage() {}

func (x *BatchedAttestation) ProtoReflect() protoreflect.Message {
	mi := &file_partial_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchedAttestation.ProtoReflect.Descriptor instead.
func (*BatchedAttestation) Descriptor() ([]byte, []int) {
	return file_partial_proto_rawDescGZIP(), []int{1}
}

func (x *BatchedAttestation) GetAttestationData() []byte {
	if x != nil {
		return x.AttestationData
	}
	return nil
}

func (x *BatchedAttestation) GetAttestorIndices() []uint32 {
	if x != nil {
		return x.AttestorIndices
	}
	return nil
}

func (x *BatchedAttestation) GetSignatures() [][]byte {
	if x != nil {
		return x.Signatures
	}
	return nil
}

// PartsMetadata is the gossip-layer advertisement for one bucket: fixed-width bitmaps over the
// committee index space. requests is a NON-PERSISTENT IWANT — the receiver satisfies what it
// can on its next tick and forgets the rest.
type PartsMetadata struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Slot            uint32                 `protobuf:"varint,1,opt,name=slot,proto3" json:"slot,omitempty"` // redundant with attestation_data, for debuggability
	AttestationData []byte                 `protobuf:"bytes,2,opt,name=attestation_data,json=attestationData,proto3" json:"attestation_data,omitempty"`
	Available       []byte                 `protobuf:"bytes,3,opt,name=available,proto3" json:"available,omitempty"` // bitmap[committeeSize] — positions we hold (validated only)
	Requests        []byte                 `protobuf:"bytes,4,opt,name=requests,proto3" json:"requests,omitempty"`   // bitmap[committeeSize] — positions we want; non-persistent
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PartsMetadata) Reset() {
	*x = PartsMetadata{}
	mi := &file_partial_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PartsMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PartsMetadata) ProtoMessage() {}

func (x *PartsMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_partial_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PartsMetadata.ProtoReflect.Descriptor instead.
func (*PartsMetadata) Descriptor() ([]byte, []int) {
	return file_partial_proto_rawDescGZIP(), []int{2}
}

func (x *PartsMetadata) GetSlot() uint32 {
	if x != nil {
		return x.Slot
	}
	return 0
}

func (x *PartsMetadata) GetAttestationData() []byte {
	if x != nil {
		return x.AttestationData
	}
	return nil
}

func (x *PartsMetadata) GetAvailable() []byte {
	if x != nil {
		return x.Available
	}
	return nil
}

func (x *PartsMetadata) GetRequests() []byte {
	if x != nil {
		return x.Requests
	}
	return nil
}

// ControlEnvelope is one (peer, tick)'s metadata payload (the extension's PartsMetadata field).
type ControlEnvelope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadatas     []*PartsMetadata       `protobuf:"bytes,1,rep,name=metadatas,proto3" json:"metadatas,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControlEnvelope) Reset() {
	*x = ControlEnvelope{}
	mi := &file_partial_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlEnvelope) ProtoMessage() {}

func (x *ControlEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_partial_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlEnvelope.ProtoReflect.Descriptor instead.
func (*ControlEnvelope) Descriptor() ([]byte, []int) {
	return file_partial_proto_rawDescGZIP(), []int{3}
}

func (x *ControlEnvelope) GetMetadatas() []*PartsMetadata {
	if x != nil {
		return x.Metadatas
	}
	return nil
}

// BatchedAttestationEnvelope is one (peer, tick)'s data payload (the extension's
// PartialMessage field).
type BatchedAttestationEnvelope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Batches       []*BatchedAttestation  `protobuf:"bytes,1,rep,name=batches,proto3" json:"batches,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchedAttestationEnvelope) Reset() {
	*x = BatchedAttestationEnvelope{}
	mi := &file_partial_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchedAttestationEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchedAttestationEnvelope) ProtoMessage() {}

func (x *BatchedAttestationEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_partial_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchedAttestationEnvelope.ProtoReflect.Descriptor instead.
func (*BatchedAttestationEnvelope) Descriptor() ([]byte, []int) {
	return file_partial_proto_rawDescGZIP(), []int{4}
}

func (x *BatchedAttestationEnvelope) GetBatches() []*BatchedAttestation {
	if x != nil {
		return x.Batches
	}
	return nil
}

var File_partial_proto protoreflect.FileDescriptor

const file_partial_proto_rawDesc = "" +
	"\n" +
	"\rpartial.proto\x12\x05block\"y\n" +
	"\x0ePartialAttData\x12\x12\n" +
	"\x04slot\x18\x01 \x01(\rR\x04slot\x12\x16\n" +
	"\x06subnet\x18\x02 \x01(\rR\x06subnet\x12!\n" +
	"\fvoted_origin\x18\x03 \x01(\rR\vvotedOrigin\x12\x18\n" +
	"\apayload\x18\x04 \x01(\fR\apayload\"\x8a\x01\n" +
	"\x12BatchedAttestation\x12)\n" +
	"\x10attestation_data\x18\x01 \x01(\fR\x0fattestationData\x12)\n" +
	"\x10attestor_indices\x18\x02 \x03(\rR\x0fattestorIndices\x12\x1e\n" +
	"\n" +
	"signatures\x18\x03 \x03(\fR\n" +
	"signatures\"\x88\x01\n" +
	"\rPartsMetadata\x12\x12\n" +
	"\x04slot\x18\x01 \x01(\rR\x04slot\x12)\n" +
	"\x10attestation_data\x18\x02 \x01(\fR\x0fattestationData\x12\x1c\n" +
	"\tavailable\x18\x03 \x01(\fR\tavailable\x12\x1a\n" +
	"\brequests\x18\x04 \x01(\fR\brequests\"E\n" +
	"\x0fControlEnvelope\x122\n" +
	"\tmetadatas\x18\x01 \x03(\v2\x14.block.PartsMetadataR\tmetadatas\"Q\n" +
	"\x1aBatchedAttestationEnvelope\x123\n" +
	"\abatches\x18\x01 \x03(\v2\x19.block.BatchedAttestationR\abatchesB\x1fZ\x1dgithub.com/ethp2p/slot-sim/pbb\x06proto3"

var (
	file_partial_proto_rawDescOnce sync.Once
	file_partial_proto_rawDescData []byte
)

func file_partial_proto_rawDescGZIP() []byte {
	file_partial_proto_rawDescOnce.Do(func() {
		file_partial_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_partial_proto_rawDesc), len(file_partial_proto_rawDesc)))
	})
	return file_partial_proto_rawDescData
}

var file_partial_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_partial_proto_goTypes = []any{
	(*PartialAttData)(nil),             // 0: block.PartialAttData
	(*BatchedAttestation)(nil),         // 1: block.BatchedAttestation
	(*PartsMetadata)(nil),              // 2: block.PartsMetadata
	(*ControlEnvelope)(nil),            // 3: block.ControlEnvelope
	(*BatchedAttestationEnvelope)(nil), // 4: block.BatchedAttestationEnvelope
}
var file_partial_proto_depIdxs = []int32{
	2, // 0: block.ControlEnvelope.metadatas:type_name -> block.PartsMetadata
	1, // 1: block.BatchedAttestationEnvelope.batches:type_name -> block.BatchedAttestation
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_partial_proto_init() }
func file_partial_proto_init() {
	if File_partial_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_partial_proto_rawDesc), len(file_partial_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_partial_proto_goTypes,
		DependencyIndexes: file_partial_proto_depIdxs,
		MessageInfos:      file_partial_proto_msgTypes,
	}.Build()
	File_partial_proto = out.File
	file_partial_proto_goTypes = nil
	file_partial_proto_depIdxs = nil
}
