// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v7.34.1
// source: sync.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SyncMessage is the SyncCommitteeMessage wire message (~144 B), one per committee member per
// slot, published on its subcommittee's subnet. It votes the head block at
// min(block_seen, deadline) — un-gated by data availability (unlike attestations) — so
// voted_origin records the voted block's origin (proposer node) or a sentinel (max uint32)
// for the prior head, the measurable output of the block→sync causal edge.
type SyncMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slot          uint32                 `protobuf:"varint,1,opt,name=slot,proto3" json:"slot,omitempty"`
	Subnet        uint32                 `protobuf:"varint,2,opt,name=subnet,proto3" json:"subnet,omitempty"`                              // subcommittee → subnet, 0 .. sync_subnets-1
	Origin        uint32                 `protobuf:"varint,3,opt,name=origin,proto3" json:"origin,omitempty"`                              // publishing member node (gossip origin; for the loopback skip)
	VotedOrigin   uint32                 `protobuf:"varint,4,opt,name=voted_origin,json=votedOrigin,proto3" json:"voted_origin,omitempty"` // voted block's origin, or a sentinel (max uint32) for prior head
	Payload       []byte                 `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"`                             // random filler so the marshaled message ≈ 144 B
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncMessage) Reset() {
	*x = SyncMessage{}
	mi := &file_sync_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncMessage) ProtoMessage() {}

func (x *SyncMessage) ProtoReflect() protoreflect.Message {
	mi := &file_sync_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncMessage.ProtoReflect.Descriptor instead.
func (*SyncMessage) Descriptor() ([]byte, []int) {
	return file_sync_proto_rawDescGZIP(), []int{0}
}

func (x *SyncMessage) GetSlot() uint32 {
	if x != nil {
		return x.Slot
	}
	return 0
}

func (x *SyncMessage) GetSubnet() uint32 {
	if x != nil {
		return x.Subnet
	}
	return 0
}

func (x *SyncMessage) GetOrigin() uint32 {
	if x != nil {
		return x.Origin
	}
	return 0
}

func (x *SyncMessage) GetVotedOrigin() uint32 {
	if x != nil {
		return x.VotedOrigin
	}
	return 0
}

func (x *SyncMessage) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

// SyncContribution is the SignedContributionAndProof wire message (~360 B), published on the
// single global sync_committee_contribution_and_proof topic at the contribution deadline. Each
// subnet has ~target_aggregators aggregators; every aggregator publishes one distinct
// contribution. origin carries the aggregator node, which both makes the contribution distinct
// (so gossipsub does not dedup them) and is the gossip origin for the loopback skip.
type SyncContribution struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slot          uint32                 `protobuf:"varint,1,opt,name=slot,proto3" json:"slot,omitempty"`
	Subnet        uint32                 `protobuf:"varint,2,opt,name=subnet,proto3" json:"subnet,omitempty"`  // subcommittee (for distinctness; the topic is global)
	Origin        uint32                 `protobuf:"varint,3,opt,name=origin,proto3" json:"origin,omitempty"`  // aggregator node (its key makes the contribution distinct; gossip origin)
	Payload       []byte                 `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"` // random filler so the marshaled message ≈ 360 B
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncContribution) Reset() {
	*x = SyncContribution{}
	mi := &file_sync_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncContribution) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncContribution) ProtoMessage() {}

func (x *SyncContribution) ProtoReflect() protoreflect.Message {
	mi := &file_sync_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncContribution.ProtoReflect.Descriptor instead.
func (*SyncContribution) Descriptor() ([]byte, []int) {
	return file_sync_proto_rawDescGZIP(), []int{1}
}

func (x *SyncContribution) GetSlot() uint32 {
	if x != nil {
		return x.Slot
	}
	return 0
}

func (x *SyncContribution) GetSubnet() uint32 {
	if x != nil {
		return x.Subnet
	}
	return 0
}

func (x *SyncContribution) GetOrigin() uint32 {
	if x != nil {
		return x.Origin
	}
	return 0
}

func (x *SyncContribution) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

var File_sync_proto protoreflect.FileDescriptor

const file_sync_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"sync.proto\x12\x05block\"\x8e\x01\n" +
	"\vSyncMessage\x12\x12\n" +
	"\x04slot\x18\x01 \x01(\rR\x04slot\x12\x16\n" +
	"\x06subnet\x18\x02 \x01(\rR\x06subnet\x12\x16\n" +
	"\x06origin\x18\x03 \x01(\rR\x06origin\x12!\n" +
	"\fvoted_origin\x18\x04 \x01(\rR\vvotedOrigin\x12\x18\n" +
	"\apayload\x18\x05 \x01(\fR\apayload\"p\n" +
	"\x10SyncContribution\x12\x12\n" +
	"\x04slot\x18\x01 \x01(\rR\x04slot\x12\x16\n" +
	"\x06subnet\x18\x02 \x01(\rR\x06subnet\x12\x16\n" +
	"\x06origin\x18\x03 \x01(\rR\x06origin\x12\x18\n" +
	"\apayload\x18\x04 \x01(\fR\apayloadB\x1fZ\x1dgithub.com/ethp2p/slot-sim/pbb\x06proto3"

var (
	file_sync_proto_rawDescOnce sync.Once
	file_sync_proto_rawDescData []byte
)

func file_sync_proto_rawDescGZIP() []byte {
	file_sync_proto_rawDescOnce.Do(func() {
		file_sync_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sync_proto_rawDesc), len(file_sync_proto_rawDesc)))
	})
	return file_sync_proto_rawDescData
}

var file_sync_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_sync_proto_goTypes = []any{
	(*SyncMessage)(nil),      // 0: block.SyncMessage
	(*SyncContribution)(nil), // 1: block.SyncContribution
}
var file_sync_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_sync_proto_init() }
func file_sync_proto_init() {
	if File_sync_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sync_proto_rawDesc), len(file_sync_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sync_proto_goTypes,
		DependencyIndexes: file_sync_proto_depIdxs,
		MessageInfos:      file_sync_proto_msgTypes,
	}.Build()
	File_sync_proto = out.File
	file_sync_proto_goTypes = nil
	file_sync_proto_depIdxs = nil
}
